name: flutter_youtube
description: Flutter Plugin to play youtube Videos
version: 1.1.4
author: Karthik Ponnam <ponnamkarthik3@gmail.com>
homepage: https://github.com/PonnamKarthik/FlutterYoutube

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0

flutter:
  plugin:
    androidPackage: io.github.ponnamkarthik.flutteryoutube
    pluginClass: FlutterYoutubePlugin

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=0.1.4"
