name: loadmore
description: listview scroll to bottom ,can load more data. help developer paging load data.
version: 1.0.2
author: caijinglong<cjl_spy@163.com>
email: cjl_spy@163.com
homepage: https://github.com/OpenFlutter/flutter_listview_loadmore/tree/master/loadmore

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.3.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
